using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MeterOff.Core.Models.Dto.SmallDepartmentDtos
{
    public class SmallDepartmentDto
    {
        public int Id { get; set; }
        public int MainDepartmentId { get; set; }
        public int SectionId { get; set; }
        public int CodeAutoGenerated { get; set; }
        public string SouthCairoCode { get; set; } //كود جنوب القاهرة
        public int AccountReferenceCounter { get; set; } //عدد المشتركين فى كل ادارة
        public string Name { get; set; }
        public int? RegionCode { get; set; }

    }
}
