using MeterOff.Core.Models.Base;
using MeterOff.Core.Models.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MeterOff.Core.Models.Infrastructure
{
    public class CompanyHierarchical : BaseEntity
    {
        [MaxLength(100)]
        public string Name { get; set; }
        public int? ParentId { get; set; }
        public int OrganizationLevelId { get; set; }
        public int? RegionCode { get; set; }
        public int CodeAutoGenerated { get; set; }
        public string SouthCairoCode { get; set; }
        public int AccountReferenceCounter { get; set; }
        public virtual ICollection<ApplicationUser> Users { get; set; }
        //public virtual ICollection<Technician> Technicians { get; set; }
    }
}
