using MeterOff.Core.Models.Base;
using MeterOff.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using MeterOff.Core.Models.Infrastructure;

namespace MeterOff.Core.Models
{
    public class MainDepartment : BaseEntity
    {
        [ForeignKey("Section")]
        public int sectionId { get; set; }
        public virtual Section section { get; set; }

        [MaxLength(100)]
        public string Name { get; set; }
        public int? RegionCode { get; set; }
        public int CodeAutoGenerated { get; set; }
        public string SouthCairoCode { get; set; } //كود جنوب القاهرة
        public int AccountReferenceCounter { get; set; } //عدد المشتركين فى كل ادارة
        public virtual ICollection<Technician> Technicians { get; set; }



    }
}
