using MeterOff.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using MeterOff.Core.Models.Base;
using MeterOff.Core.Models.Infrastructure;
using MeterOff.Core.Models.Identity;

namespace MeterOff.Core.Models
{
    public class Section :BaseEntity
    {

        [MaxLength(100)]
        public string Name { get; set; }
        public int? RegionCode { get; set; }
        public int CodeAutoGenerated { get; set; }
        public string SouthCairoCode { get; set; } //كود جنوب القاهرة
        public int AccountReferenceCounter { get; set; } //عدد المشتركين فى كل ادارة
        public virtual ICollection<Technician> Technicians { get; set; }
        public virtual ICollection<ApplicationUser> Users { get; set; }

        //public virtual ICollection<CompanyHierarchical> OrganizationStructures { get; set; }

        //public virtual ICollection<TechnicianDepartment> EmployeeDepartments { get; set; }
    }
}
