
using MeterOff.Core.Models.Base;
using MeterOff.Core.Models.Identity;
using MeterOff.Core.Models.Infrastructure;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MeterOff.Core.Models
{
    public class SmallDepartment :BaseEntity
    {
        [ForeignKey("MainDepartment")]
        public int MainDepartmentId { get; set; }
        public virtual MainDepartment mainDepartment { get; set; }


        [ForeignKey ("Section")]
        public int SectionId { get; set; }
        public virtual Section section { get; set; }


        public int CodeAutoGenerated { get; set; }
        public string SouthCairoCode { get; set; } //كود جنوب القاهرة
        public int AccountReferenceCounter { get; set; } //عدد المشتركين فى كل ادارة

        [MaxLength(100)]
        public string Name { get; set; }
        public int? RegionCode { get; set; }
        public virtual ICollection<Technician> Technicians { get; set; }
        public virtual ICollection<ApplicationUser> ApplicationUsers { get; set; }


        //public virtual ICollection<SmallDepartment_User> SmallDepartment_Users { get; set; }
    }
}
