using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MeterOff.EF.Migrations
{
    /// <inheritdoc />
    public partial class New2 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_AspNetUsers_CompanyHierarchical_CompanyHierarchicalId",
                table: "AspNetUsers");

            migrationBuilder.DropForeignKey(
                name: "FK_PointOfSale_CompanyHierarchical_departmentId",
                table: "PointOfSale");

            migrationBuilder.DropForeignKey(
                name: "FK_Technician_CompanyHierarchical_CompanyHierarchicalId",
                table: "Technician");

            migrationBuilder.DropTable(
                name: "CompanyHierarchical");

            migrationBuilder.DropIndex(
                name: "IX_Technician_CompanyHierarchicalId",
                table: "Technician");

            migrationBuilder.DropIndex(
                name: "IX_PointOfSale_departmentId",
                table: "PointOfSale");

            migrationBuilder.DropIndex(
                name: "IX_AspNetUsers_CompanyHierarchicalId",
                table: "AspNetUsers");

            migrationBuilder.DropColumn(
                name: "CompanyHierarchicalId",
                table: "Technician");

            migrationBuilder.DropColumn(
                name: "CompanyHierarchicalId",
                table: "AspNetUsers");

            migrationBuilder.AlterColumn<int>(
                name: "departmentId",
                table: "PointOfSale",
                type: "int",
                nullable: true,
                oldClrType: typeof(int),
                oldType: "int");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "CompanyHierarchicalId",
                table: "Technician",
                type: "int",
                nullable: true);

            migrationBuilder.AlterColumn<int>(
                name: "departmentId",
                table: "PointOfSale",
                type: "int",
                nullable: false,
                defaultValue: 0,
                oldClrType: typeof(int),
                oldType: "int",
                oldNullable: true);

            migrationBuilder.AddColumn<int>(
                name: "CompanyHierarchicalId",
                table: "AspNetUsers",
                type: "int",
                nullable: true);

            migrationBuilder.CreateTable(
                name: "CompanyHierarchical",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    AccountReferenceCounter = table.Column<int>(type: "int", nullable: false),
                    CodeAutoGenerated = table.Column<int>(type: "int", nullable: false),
                    CreationTime = table.Column<DateTime>(type: "datetime2", nullable: false),
                    CreatorById = table.Column<int>(type: "int", nullable: false),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false),
                    ModificationTime = table.Column<DateTime>(type: "datetime2", nullable: true),
                    ModifiedById = table.Column<int>(type: "int", nullable: true),
                    Name = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    OrganizationLevelId = table.Column<int>(type: "int", nullable: false),
                    ParentId = table.Column<int>(type: "int", nullable: true),
                    RegionCode = table.Column<int>(type: "int", nullable: true),
                    SouthCairoCode = table.Column<string>(type: "nvarchar(max)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CompanyHierarchical", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_Technician_CompanyHierarchicalId",
                table: "Technician",
                column: "CompanyHierarchicalId");

            migrationBuilder.CreateIndex(
                name: "IX_PointOfSale_departmentId",
                table: "PointOfSale",
                column: "departmentId");

            migrationBuilder.CreateIndex(
                name: "IX_AspNetUsers_CompanyHierarchicalId",
                table: "AspNetUsers",
                column: "CompanyHierarchicalId");

            migrationBuilder.AddForeignKey(
                name: "FK_AspNetUsers_CompanyHierarchical_CompanyHierarchicalId",
                table: "AspNetUsers",
                column: "CompanyHierarchicalId",
                principalTable: "CompanyHierarchical",
                principalColumn: "Id");

            migrationBuilder.AddForeignKey(
                name: "FK_PointOfSale_CompanyHierarchical_departmentId",
                table: "PointOfSale",
                column: "departmentId",
                principalTable: "CompanyHierarchical",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_Technician_CompanyHierarchical_CompanyHierarchicalId",
                table: "Technician",
                column: "CompanyHierarchicalId",
                principalTable: "CompanyHierarchical",
                principalColumn: "Id");
        }
    }
}
